apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
  namespace: quotes-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes-service
  template:
    metadata:
      labels:
        app: quotes-service
    spec:
      containers:
        - name: quotes-service
          image: quinont/otel-quotes-services:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: quotes-ns
spec:
  selector:
    app: quotes-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
